[package]
name = "midia"
version = "0.1.1"
edition = "2021"
authors = ["levinion <levinnion@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
